### ISSUE TITLE
i found a issue

### ISSUE THREAD

**Issue by mnickhoo** [exceptionnotfound/FactoryMethodPattern#1]
when i saw a abstract sandwich class you set ingredients property that jsut getter propety when you inherite sandwich to another class in createIngredietns you add ingredient to this property that is getter property !!! not setter propery

**Comment by mnickhoo** [comment]
public List<Ingredient> Ingredients
        {
            get { return _ingredients; }
        }

**Comment by exceptionnotfound** [comment]
This is intentional.  In that design (I am assuming Factory Method pattern due to the details here) the ingredients are created as part of the constructor.
