### ISSUE TITLE
Why do you use the Element for Visitor pattern?

### ISSUE THREAD

**Issue by tigertv** [exceptionnotfound/FactoryMethodPattern#4]
Hi, Matthew!
Why do you use the abstract Element and not the concrete Employee for Visitor pattern?

https://github.com/exceptionnotfound/DesignPatterns/blob/ff35265da5bd626be92c5e68927a89d105f6fbed/Visitor/Patron.cs#L12-L15

**Comment by exceptionnotfound** [comment]
Primarily to show how this might work in a real-world project that would have more Concrete Elements than just Employees.  If this *was* a real-world project, the Element class would probably be unnecessary, because we only have Employees.

**Comment by tigertv** [comment]
Why is not this way? If there would be 3 elements.
```c#
interface IVisitor
{
    void Visit(Element1 element);
    void Visit(Element2 element);
    void Visit(Element3 element);
}
```
